### ISSUE TITLE
Terraformer fails when running validate command

### ISSUE THREAD

**Issue by KevinDW-Fluxys** [gardener/terraformer#139]
**How to categorize this issue?**
/kind bug

**What happened**:
I have set up a validate command as shown in the example in the documentation.
When starting the container with a validate command I get  the message   `Success! The configuration is valid.` followed by an error:  `Error: Insufficient features blocks  on <empty> line 0:  (source code not available)`
The second error seems to come from running the plan command. Any changes I make to the configmap seem to have no impact on the message (i tried introducing some syntax errors but the error remains the same)
When running the apply command I get the same error directly on the apply command. I believe rbac is properly set up (i followed the example) because when i take my serviceaccount away, I get an error about permissions.

The logs:
```
{"level":"info","ts":"2023-08-28T09:56:08.552Z","msg":"terraform process finished successfully","step":"executeTerraform","command":"init"}
{"level":"info","ts":"2023-08-28T09:56:08.557Z","msg":"executing terraform","step":"executeTerraform","command":"validate","args":"-chdir=/tf validate -no-color"}
Success! The configuration is valid.

{"level":"info","ts":"2023-08-28T09:56:09.719Z","msg":"terraform process finished successfully","step":"executeTerraform","command":"validate"}
{"level":"info","ts":"2023-08-28T09:56:09.719Z","msg":"executing terraform","step":"executeTerraform","command":"plan","args":"-chdir=/tf plan -no-color -var-file=/tfvars/terraform.tfvars -parallelism=4 -detailed-exitcode -state=/tfstate/terraform.tfstate"}

Error: Insufficient features blocks

  on <empty> line 0:
  (source code not available)

At least 1 "features" blocks are required.
{"level":"error","ts":"2023-08-28T09:56:11.366Z","msg":"terraform process finished with error","step":"executeTerraform","command":"plan","error":"exit status 1","stacktrace":"github.com/gardener/terraformer/pkg/terraformer.(*Terraformer).executeTerraform\n\t/go/src/github.com/gardener/terraformer/pkg/terraformer/terraformer.go:299\ngithub.com/gardener/terraformer/pkg/terraformer.(*Terraformer).execute\n\t/go/src/github.com/gardener/terraformer/pkg/terraformer/terraformer.go:210\ngithub.com/gardener/terraformer/pkg/terraformer.(*Terraformer).Run\n\t/go/src/github.com/gardener/terraformer/pkg/terraformer/terraformer.go:117\ngithub.com/gardener/terraformer/cmd/terraformer/app.addSubcommand.func1\n\t/go/src/github.com/gardener/terraformer/cmd/terraformer/app/terraformer.go:110\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/gardener/terraformer/vendor/github.com/spf13/cobra/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/gardener/terraformer/vendor/github.com/spf13/cobra/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/gardener/terraformer/vendor/github.com/spf13/cobra/command.go:968\nmain.main\n\t/go/src/github.com/gardener/terraformer/cmd/terraformer/main.go:25\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":"2023-08-28T09:56:11.378Z","msg":"triggering final state update before exiting","step":"finalStateUpdate","timeout":"1h0m0s"}
{"level":"info","ts":"2023-08-28T09:56:11.387Z","msg":"successfully stored terraform state","step":"finalStateUpdate"}
{"level":"error","ts":"2023-08-28T09:56:11.387Z","msg":"error running terraformer","error":"error executing terraform plan: terraform command failed with exit code 1: exit status 1","stacktrace":"main.main\n\t/go/src/github.com/gardener/terraformer/cmd/terraformer/main.go:27\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

**What you expected to happen**:
- The pod should run without errors 
- Changes in the config map should reflect in the error
- The error should clearly reflect what is wrong

**How to reproduce it (as minimally and precisely as possible)**:
- Run a pod with terraformer v2.23.0 with a validate command as such
```
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-terraformer
  namespace: terraformer-poc
spec:
  activeDeadlineSeconds: 1800
  containers:
  - name: terraform
    image: ***/terraformer:v2.23.0
    imagePullPolicy: IfNotPresent
    command:
      - /terraformer 
      - validate
      - --zap-log-level=debug
      - --configuration-configmap-name=dev-hello-world.tf-config
      - --state-configmap-name=dev-hello-world.tf-state
      - --variables-secret-name=dev-hello-world.tf-vars
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /terraform-termination-log
  restartPolicy: Never
  serviceAccountName: terraformer
  terminationGracePeriodSeconds: 600
```
- Create configmaps as such:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-hello-world.tf-config
  namespace: terraformer-poc
data:
  providers.tf: |
    terraform {
      required_version = ">=0.12"
      required_providers {
        azurerm = {
          source  = "hashicorp/azurerm"
          version = "~>2.0"
        }
      }
    }
    provider "azurerm" {
      features {}
    }
  main.tf: |
    resource "azurerm_resource_group" "rg" {
      location = "westeurope"
      name     = "terraformer-poc"
    }
  variables.tf: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-hello-world.tf-state
  namespace: terraformer-poc
data:
  terraform.tfstate: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-hello-world.tf-vars
  namespace: terraformer-poc
type: Opaque
stringData:
  terraform.tfvars: ""
```

**Anything else we need to know?**:
I'm authenticating to Azure with env vars containing an SPN according to the terraform docs. I have also tried directly placing the credentials in the provider block but its the same result. I'm guessing the problem could be with authentication, in which case the error should more clearly reflect the reason. (but ofcourse im not sure about that)

**Environment**:

- Gardener version (if relevant): NA
- Terraformer version: 2.23.0
- Kubernetes version (use `kubectl version`): 1.27.3
- Cloud provider or hardware configuration: Azure 
- Others:
